# Pussy Kiss
[colors]
foreground = "#babab9"
background = "#1c0c28"
cursor_bg = "#fcfad6"
cursor_fg = "#000000"
selection_bg = "#685788"
selection_fg = "#ffffff"

ansi = ["#0a4c62","#99246e","#5cb1b3","#eab9a8","#7a99bb","#57225e","#7e83cc","#afaadf"]
brights = ["#201637","#c87272","#0a6c7e","#c058d5","#45a4e2","#d3e6af","#150606","#0a6c7e"]
